# PowerShell script for Step 1.4: Generate Rename Script
# Golden Wings Documentary - File Organization Project
# Author: AI Assistant for Caleb Stewart
# Date: September 27, 2025

[CmdletBinding()]
param(
    [string]$InputFile,
    [string]$OutputScript,
    [switch]$IncludeBackup,
    [switch]$DryRun,
    [switch]$NoPause
)

Write-Host "🛠️  Step 1.4: Generate Rename Script" -ForegroundColor Yellow
Write-Host "===================================" -ForegroundColor Yellow
Write-Host ""

# Resolve working directory and default paths
$scriptDir = if ($PSScriptRoot) {
    $PSScriptRoot
} elseif ($MyInvocation.MyCommand.Path) {
    Split-Path -Path $MyInvocation.MyCommand.Path -Parent
} else {
    Get-Location | Select-Object -ExpandProperty Path
}

if ([string]::IsNullOrWhiteSpace($InputFile)) {
    $InputFile = Join-Path -Path $scriptDir -ChildPath "rename_mappings.json"
}

if ([string]::IsNullOrWhiteSpace($OutputScript)) {
    $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $OutputScript = Join-Path -Path $scriptDir -ChildPath "execute_renames_$timestamp.ps1"
}

Write-Host "📁 Working directory: $scriptDir" -ForegroundColor Cyan
Write-Host "📄 Reading rename mappings: $InputFile" -ForegroundColor Cyan
Write-Host "📝 Output script: $OutputScript" -ForegroundColor Cyan
if ($IncludeBackup) {
    Write-Host "💾 Backup mode: Enabled" -ForegroundColor Green
}
if ($DryRun) {
    Write-Host "👁️  Dry run mode: Enabled" -ForegroundColor Yellow
}
Write-Host ""

# Check if input file exists
if (-not (Test-Path -LiteralPath $InputFile)) {
    Write-Host "❌ ERROR: Rename mappings file not found at '$InputFile'. Run Step 1.3 first." -ForegroundColor Red
    exit 1
}

# Load rename mappings
try {
    $jsonContent = Get-Content -LiteralPath $InputFile -Raw -Encoding UTF8
    $mappingData = $jsonContent | ConvertFrom-Json -ErrorAction Stop
    $renameMappings = @($mappingData.RenameMappings)
    Write-Host "✅ Loaded $($renameMappings.Count) rename mappings" -ForegroundColor Green
} catch {
    Write-Host "❌ ERROR: Failed to load rename mappings - $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

if ($renameMappings.Count -eq 0) {
    Write-Host "⚠️  WARNING: No rename mappings found in input file." -ForegroundColor Yellow
    exit 0
}

Write-Host ""

# Validate all source files exist
Write-Host "🔍 Validating source files..." -ForegroundColor Cyan
$validMappings = @()
$missingFiles = @()

foreach ($mapping in $renameMappings) {
    if (-not $mapping.OldPath -or -not (Test-Path -LiteralPath $mapping.OldPath)) {
        $missingFiles += $mapping
        Write-Host "   ❌ Missing: $($mapping.OldFileName)" -ForegroundColor Red
    } else {
        $validMappings += $mapping
        Write-Host "   ✅ Found: $($mapping.OldFileName)" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "📊 Validation Results:" -ForegroundColor Cyan
Write-Host "   ✅ Valid mappings: $($validMappings.Count)" -ForegroundColor Green
Write-Host "   ❌ Missing files: $($missingFiles.Count)" -ForegroundColor Red

if ($missingFiles.Count -gt 0) {
    Write-Host ""
    Write-Host "⚠️  WARNING: Some source files are missing. The generated script will skip these files." -ForegroundColor Yellow
}

if ($validMappings.Count -eq 0) {
    Write-Host "❌ ERROR: No valid files to rename. Check file paths and try again." -ForegroundColor Red
    exit 1
}

Write-Host ""

# Generate the rename execution script
Write-Host "🛠️  Generating rename execution script..." -ForegroundColor Cyan

$scriptContent = @"
# Golden Wings Documentary - File Rename Execution Script
# Generated by Step 1.4 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# Source mappings: $((Resolve-Path -LiteralPath $InputFile).Path)

[CmdletBinding()]
param(
    [switch]`$WhatIf,
    [switch]`$Force,
    [switch]`$NoBackup,
    [string]`$LogFile
)

Write-Host "🎬 Golden Wings File Rename Execution" -ForegroundColor Yellow
Write-Host "====================================" -ForegroundColor Yellow
Write-Host ""

# Initialize logging
if ([string]::IsNullOrWhiteSpace(`$LogFile)) {
    `$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    `$LogFile = "rename_execution_log_`$timestamp.txt"
}

function Write-Log {
    param([string]`$Message, [string]`$Level = "INFO")
    `$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    `$logEntry = "[`$timestamp] [`$Level] `$Message"
    Add-Content -Path `$LogFile -Value `$logEntry -Encoding UTF8
    
    switch (`$Level) {
        "ERROR" { Write-Host `$Message -ForegroundColor Red }
        "WARNING" { Write-Host `$Message -ForegroundColor Yellow }
        "SUCCESS" { Write-Host `$Message -ForegroundColor Green }
        default { Write-Host `$Message -ForegroundColor White }
    }
}

# Initialize counters
`$summary = @{
    TotalFiles = $($validMappings.Count)
    Renamed = 0
    Skipped = 0
    Errors = 0
    BackedUp = 0
}

Write-Log "Starting rename operation for `$(`$summary.TotalFiles) files"
Write-Log "Log file: `$LogFile"
Write-Log "What-If mode: `$(`$WhatIf.IsPresent)"
Write-Log "Force mode: `$(`$Force.IsPresent)"
Write-Log "Backup disabled: `$(`$NoBackup.IsPresent)"
Write-Host ""

# Create backup directory if needed
`$backupDir = `$null
if (-not `$NoBackup -and -not `$WhatIf) {
    `$backupDir = "backup_$(Get-Date -Format "yyyyMMdd_HHmmss")"
    try {
        New-Item -Path `$backupDir -ItemType Directory -Force | Out-Null
        Write-Log "Created backup directory: `$backupDir" "SUCCESS"
    } catch {
        Write-Log "Failed to create backup directory: `$(`$_.Exception.Message)" "ERROR"
        if (-not `$Force) {
            Write-Log "Aborting due to backup directory creation failure. Use -Force to continue without backup." "ERROR"
            exit 1
        }
        `$backupDir = `$null
    }
}

# Process each rename mapping
"@

# Add individual rename operations
foreach ($mapping in $validMappings) {
    $oldPathEscaped = $mapping.OldPath -replace "'", "''"
    $newPathEscaped = $mapping.NewPath -replace "'", "''"
    $oldFileNameEscaped = $mapping.OldFileName -replace "'", "''"
    $newFileNameEscaped = $mapping.NewFileName -replace "'", "''"
    
    $scriptContent += @"

# Rename: $($mapping.OldFileName) → $($mapping.NewFileName)
try {
    `$oldPath = '$oldPathEscaped'
    `$newPath = '$newPathEscaped'
    `$oldFileName = '$oldFileNameEscaped'
    `$newFileName = '$newFileNameEscaped'
    
    Write-Log "Processing: `$oldFileName → `$newFileName"
    
    # Verify source file still exists
    if (-not (Test-Path -LiteralPath `$oldPath)) {
        Write-Log "Source file not found: `$oldPath" "WARNING"
        `$summary.Skipped++
        continue
    }
    
    # Check if destination already exists
    if ((Test-Path -LiteralPath `$newPath) -and -not `$Force) {
        Write-Log "Destination already exists: `$newPath (use -Force to overwrite)" "WARNING"
        `$summary.Skipped++
        continue
    }
    
    # Create destination directory if needed
    `$destDir = Split-Path -Path `$newPath -Parent
    if (-not (Test-Path -Path `$destDir)) {
        if (-not `$WhatIf) {
            New-Item -Path `$destDir -ItemType Directory -Force | Out-Null
            Write-Log "Created directory: `$destDir"
        } else {
            Write-Log "Would create directory: `$destDir"
        }
    }
    
    # Create backup if enabled
    if (`$backupDir -and -not `$WhatIf) {
        try {
            `$backupPath = Join-Path -Path `$backupDir -ChildPath `$oldFileName
            Copy-Item -LiteralPath `$oldPath -Destination `$backupPath -Force
            Write-Log "Backed up: `$oldFileName"
            `$summary.BackedUp++
        } catch {
            Write-Log "Backup failed for `$oldFileName`: `$(`$_.Exception.Message)" "WARNING"
        }
    }
    
    # Perform the rename
    if (`$WhatIf) {
        Write-Log "Would rename: `$oldPath → `$newPath"
    } else {
        Move-Item -LiteralPath `$oldPath -Destination `$newPath -Force
        Write-Log "Renamed: `$oldFileName → `$newFileName" "SUCCESS"
    }
    
    `$summary.Renamed++
    
} catch {
    Write-Log "Error renaming `$oldFileName`: `$(`$_.Exception.Message)" "ERROR"
    `$summary.Errors++
}
"@
}

# Add summary and cleanup
$scriptContent += @"

Write-Host ""
Write-Host "====================================" -ForegroundColor Yellow
Write-Host "📊 RENAME OPERATION SUMMARY" -ForegroundColor Yellow
Write-Host "====================================" -ForegroundColor Yellow
Write-Log "Total files: `$(`$summary.TotalFiles)"
Write-Log "Successfully renamed: `$(`$summary.Renamed)" "SUCCESS"
Write-Log "Skipped: `$(`$summary.Skipped)" "WARNING"
Write-Log "Errors: `$(`$summary.Errors)" "ERROR"
if (`$backupDir) {
    Write-Log "Files backed up: `$(`$summary.BackedUp)" "SUCCESS"
    Write-Log "Backup location: `$backupDir"
}
Write-Log "Log file: `$LogFile"

if (`$summary.Errors -gt 0) {
    Write-Log "Rename operation completed with errors. Check log for details." "WARNING"
    exit 1
} else {
    Write-Log "Rename operation completed successfully!" "SUCCESS"
    exit 0
}
"@

# Write the script file
try {
    $scriptContent | Out-File -LiteralPath $OutputScript -Encoding UTF8
    Write-Host "✅ Generated rename script: $OutputScript" -ForegroundColor Green
} catch {
    Write-Host "❌ ERROR: Failed to write script file - $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

Write-Host ""

# Generate usage instructions
$usageInstructions = @"
# Golden Wings Rename Script Usage Instructions
# Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Script Location
$OutputScript

## Usage Options

### 1. Preview Mode (Recommended First)
```powershell
pwsh -NoProfile -File "$OutputScript" -WhatIf
```
This shows what would be renamed without making any changes.

### 2. Standard Execution with Backup
```powershell
pwsh -NoProfile -File "$OutputScript"
```
Renames all files and creates backup copies in a timestamped backup folder.

### 3. Execution without Backup (Use with caution)
```powershell
pwsh -NoProfile -File "$OutputScript" -NoBackup
```
Renames files without creating backups. Only use if you have other backups.

### 4. Force Overwrite Existing Files
```powershell
pwsh -NoProfile -File "$OutputScript" -Force
```
Overwrites destination files if they already exist.

### 5. Custom Log File
```powershell
pwsh -NoProfile -File "$OutputScript" -LogFile "my_rename_log.txt"
```
Saves execution log to a custom file location.

## Safety Features

- **Backup Creation**: Automatic backup of original files (unless -NoBackup)
- **Collision Detection**: Warns about existing destination files
- **Directory Creation**: Automatically creates destination directories
- **Comprehensive Logging**: Detailed log of all operations
- **Error Recovery**: Continues processing even if individual files fail
- **What-If Mode**: Preview changes before applying

## File Summary
- Total mappings loaded: $($renameMappings.Count)
- Valid files found: $($validMappings.Count)
- Missing source files: $($missingFiles.Count)

## Recommended Workflow
1. Run with -WhatIf first to preview changes
2. Review the proposed renames carefully
3. Run without -WhatIf to execute (backup will be created automatically)
4. Check the execution log for any issues
5. Verify renamed files are correct

## Rollback Instructions
If you need to restore original filenames:
1. Locate the backup folder (backup_YYYYMMDD_HHMMSS)
2. Copy files from backup folder back to their original locations
3. Use the execution log to identify which files were renamed

"@

$instructionsFile = Join-Path -Path $scriptDir -ChildPath "rename_execution_instructions.txt"
try {
    $usageInstructions | Out-File -LiteralPath $instructionsFile -Encoding UTF8
    Write-Host "📋 Generated usage instructions: $instructionsFile" -ForegroundColor Green
} catch {
    Write-Host "⚠️  WARNING: Failed to write instructions file - $($_.Exception.Message)" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "====================================" -ForegroundColor Yellow
Write-Host "📊 SCRIPT GENERATION SUMMARY" -ForegroundColor Yellow
Write-Host "====================================" -ForegroundColor Yellow
Write-Host "📝 Generated script: $OutputScript" -ForegroundColor Cyan
Write-Host "📋 Usage instructions: $instructionsFile" -ForegroundColor Cyan
Write-Host "📄 Total rename operations: $($validMappings.Count)" -ForegroundColor Green
if ($missingFiles.Count -gt 0) {
    Write-Host "⚠️  Missing source files: $($missingFiles.Count)" -ForegroundColor Yellow
}
Write-Host ""

Write-Host "🎉 Step 1.4 Complete! Ready for Step 1.5 - Execute Renames" -ForegroundColor Green
Write-Host ""
Write-Host "💡 Next steps:" -ForegroundColor Cyan
Write-Host "   1. Review the generated script: $OutputScript" -ForegroundColor White
Write-Host "   2. Test with: pwsh -NoProfile -File `"$OutputScript`" -WhatIf" -ForegroundColor White
Write-Host "   3. Execute with: pwsh -NoProfile -File `"$OutputScript`"" -ForegroundColor White
Write-Host ""

if (-not $NoPause) {
    Write-Host "Press any key to exit..." -ForegroundColor Gray
    try {
        $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    } catch {
        # Ignore when host doesn't support interactive key reads
    }
}
